dist: xenial
language: cpp
compiler: clang
sudo: true
before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-7 -y
- sudo apt-get install g++-7 -y
- sudo apt-get install python-pip -y
- pip install --user conan
script:
- conan install . -s compiler=clang -s compiler.version=6.0 -s compiler.libcxx=libstdc++11 --build=missing
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
- provider: script
  skip_cleanup: true
  script:
  - curl -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uarcsigov:$BINTRAY_API_KEY "https://api.bintray.com/content/arcsigov/otus-homework/homework/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=i386,amd64;publish=1"
